### ISSUE TITLE
formatting error in date

### ISSUE THREAD

**Issue by benmaier** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#1]
In today's version of ``SARS-CoV-2-Sequenzdaten_Deutschland.csv.xz``

in line ``408310``, date is incorrectly formatted as ``2021-12sss-02``.

**Comment by cuehs** [comment]
Dear @benmaier 
Thank you for your comment. 
This issue should be fixed with today's data upload.

**Comment by benmaier** [comment]
cool, thanks! do you mean in an update later today? because it's still in there :)

**Comment by cuehs** [comment]
I mean tomorrow morning with the usual 6am update.

**Comment by benmaier** [comment]
thanks!
