### ISSUE TITLE
Ein paar Labore geben das Probendatum fälschlicherweise gleich dem Submissiondatum an

### ISSUE THREAD

**Issue by corneliusroemer** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#10]
Mir ist aufgefallen, dass es ein paar Submissions gibt mit `draw_date == processing_date`, siehe die Delay-Verteilung hier:
![image](https://user-images.githubusercontent.com/25161793/147694653-d4f9e952-a3ec-4107-821a-98aeedddb865.png)
https://github.com/corneliusroemer/desh-data/blob/main/plots/sequencing_delay.png

Weniger als 5 Tage Delay ist schon bemerkenswert. 0 ist praktisch unmöglich. Die Probe muss ja erst vom Patienten zum Labor für PCR, PCR muss gemacht werden, dann Sequenzierung, das dauert Stunden bis Tage, dann Bioinformatik, dann Submission.

Viel plausibler: hier werden Daten falsch eingegeben. Interessant ist, dass vor allem ein Labor betroffen ist mit PLZ `44879`, vermutlich Eurofins MVZ Labor Gelsenkirchen.

Das hier sind sending_pc der Labore mit Delay = 0:
```
44879    2331
76131     190
13353      77
69126      18
32545      12
97422      10
48143       5
21502       3
13347       3
20095       1
```

Und das die sequencing_pc mit Delay = 0:
```
44879    2331
76131     200
13353      77
69126      18
32545      12
48143       5
21502       3
13347       3
23845       1
```

Das ist die Verteilung für das Labor mit PLZ 44879, hier scheint das also systematisch zu sein:
![sequencing_delay](https://user-images.githubusercontent.com/25161793/147695152-cd71a399-0262-41d2-be8c-7a489e09a30c.png)

Beim Sequencing Labor mit PLZ `76131` sind 0/1 Tage die Ausnahme, ziemlich sicher also Fehler, denn warum sollte es bei den paar Proben nur 0-1 Tage sein, wenn die meisten Proben 10 Tage brauchen:
![sequencing_delay](https://user-images.githubusercontent.com/25161793/147695308-44e4e5c8-34e7-424e-969d-f17d07906a21.png)

**Comment by cuehs** [comment]
@corneliusroemer Vielen Dank für deinen Hinweis. Wir haben die Anmerkungen an die entsprechenden Stellen am RKI weitergeleitet die sich dann mit den Laboren in Verbindung setzen.

**Comment by corneliusroemer** [comment]
@HannesWuensche Hier das gleiche, mich würde interessieren, ob es Rückmeldungen/Korrekturen von den Laboren gab zur Randomisierung, jetzt wo das Issue geschlossen wurde. Danke!
