### ISSUE TITLE
Dokumentation der Variablen sending lab/sequencing lab in den Metadaten unklar

### ISSUE THREAD

**Issue by SusanneReimering** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#11]
Hallo! Laut Dokumentation gibt es in den Metadaten die Variablen SENDING_LAB_PC (PLZ des sequenzierenden Labors) und PRIMEDIAGNOSTIC_LAB_PC (PLZ des diagnostischen Labors). In den Metadaten vorhanden sind allerdings SENDING_LAB_PC und SEQUENCING_LAB_PC. Bezieht sich SENDING_LAB_PC damit anders als in der Doku angegeben auf das diagnostische Labor?

**Comment by cuehs** [comment]
Liebe @SusanneReimering 

Danke für den Hinweis!

SEQUENCING_LAB_PC ist das Labor welches die Sequenzierung durchgeführt hat
SENDING_LAB_PC ist das Labor welches die initiale Diagnose/PCR durchgeführt hat

**Comment by cuehs** [comment]
fixed by #12
