### ISSUE TITLE
file SARS-CoV-2-Entwicklungslinien_Deutschland.csv.xz today corrupt

### ISSUE THREAD

**Issue by entorb** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#13]
file
https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/blob/b8a8a6a155df6e7014806a5ec4c46cc850ffabb6/SARS-CoV-2-Entwicklungslinien_Deutschland.csv.xz
today only has 1MB and xz complains "Unexpected end of input".

**Comment by HannesWuensche** [comment]
He @entorb,

thank u for the notice. 
We are currently implementing an new script to publish the Data as early as possible. There seems to be a bug. 
For now I manually updated the Data. 

Best regards
@HannesWuensche 
for the Team RKI | Open Data
