### ISSUE TITLE
tag 2021-01-05 seemingly invalid

### ISSUE THREAD

**Issue by rgerhards** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#16]
This tag contains data at least for 2022-01-06, probably also for (all?) interim dates. I checked files

* `SARS-CoV-2-Entwicklungslinien_Deutschland.csv.xz`
* `SARS-CoV-2-Sequenzdaten_Deutschland.csv.xz`

In any case, it confuses scripts that walk the tags to obtain data based on reporting date (and, yes, I know it's a border case, but useful for some deep interest e.g. like sequence re-classifications and gathering some data points for nowcasting).

**Comment by HannesWuensche** [comment]
Dear @rgerhards,

could you elaborate the Issue a bit more? 

Best Regrads
@HannesWuensche 
for the Team RKI | Open Data

**Comment by rgerhards** [comment]
Thanks for having a look. I re-checked. It looks that I was wrong on `SARS-CoV-2-Entwicklungslinien_Deutschland.csv.xz`, the issue is just with `Sequenzdaten`
```
$ git checkout 2021-01-05
Note: checking out '2021-01-05'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 6ff6701 Update 2022-01-05

$ unxz -k - < SARS-CoV-2-Sequenzdaten_Deutschland.csv.xz  | grep 2022-01-04 |wc -l
4267
```

Actually, looking again at it, it looks like there was a typo inside the tag and it should be 2022 instead of 2021. `git tag` also gives:
```
2022-01-03
2022-01-04
2022-01-06
2022-01-07
```

Note the missing `-05`. Also see the commit ID in the `git checkout` output above.

**Comment by HannesWuensche** [comment]
Dear @rgerhards,

indeed a typo, fixed.

Best Regrads
@HannesWuensche
for the Team RKI | Open Data
