### ISSUE TITLE
missing tags

### ISSUE THREAD

**Issue by rgerhards** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#17]
There are tags missing for some daily updates. This causes problems when iterating over the tags as suggested in https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/issues/4#issuecomment-1000338391

Iterating over the commits is fuzzy, as not all commits are daily updates.

I suggest to add the missing tags.

Problem visible by:
See `git tag --oneline`.
head of today's output:
```
e5d1b93 (HEAD -> master, origin/master, origin/HEAD) Update 2022-02-27
478dfd9 (tag: 2022-02-26) Update 2022-02-26
6d4ac05 Update 2022-02-26
004b86d (tag: 2022-02-25) Update 2022-02-25
5018068 Update 2022-02-25
94dbeb7 (tag: 2022-02-24) Update 2022-02-24
33e9141 (tag: 2022-02-23) Update 2022-02-23
51df27c Update 2022-02-24
2349a9f (tag: 2022-02-22) Update 2022-02-22
384078e (tag: 2022-02-21) Update 2022-02-21
229f429 Update 2022-02-22
7a3eefe Update 2022-02-21
4e9fc0e Update 2022-02-20
75bf364 Update 2022-02-19
ce1a8a4 (tag: 2022-02-18) Update 2022-02-18
58631b6 Update 2022-02-18
b3d0a09 (tag: 2022-02-17) Update 2022-02-17
b8efe07 Update 2022-02-17
af9ac14 (tag: 2022-02-16) Update 2022-02-16
e39ca1d Update 2022-02-16
005f3fb (tag: 2022-02-15) Update 2022-02-15
5b7b6cc Update 2022-02-15
aae0c7d (tag: 2022-02-14) Update 2022-02-14
ba1a5e2 Update 2022-02-14
b5f9ceb (tag: 2022-02-13) Update 2022-02-13
458224a Update 2022-02-13
9dd62f8 (tag: 2022-02-12) Update 2022-02-12
1a8e56e Update 2022-02-12
4c85b7c (tag: 2022-02-11) Update 2022-02-11
b667db9 (tag: 2022-02-10) Update 2022-02-11
a46ae6d Update 2022-02-11
42ffa28 Update 2022-02-10
7c15c4d (tag: 2022-02-09) Update 2022-02-09
00d73dd (tag: 2022-02-08) Update 2022-02-08
8dc9e6d Update 2022-02-09
5dd7c01 (tag: 2022-02-07) Update 2022-02-07
607ec85 Update 2022-02-08
6bc1d8c (tag: 2022-02-06) Update 2022-02-06
776e345 Update 2022-02-07
c9de9ca Update 2022-02-06
```

**Comment by rgerhards** [comment]
@HannesWuensche Danke für die Antwort.

Das mit den 2 commits (ggf. weitere für sonstige Änderungen) ist klar. Es fehlen aber nicht tags für die Zwischen-Commits, sondern für den **finalen** Stand (wohl  meist nach Einfügung von Entwicklungslinien). So zum Beispiel auch heute, siehe #18.

Auch zwischen dem 18. und 21. gibt es keine Tags, aber sehr wohl Aktualisierungen:
```
384078e (tag: 2022-02-21) Update 2022-02-21
229f429 Update 2022-02-22
7a3eefe Update 2022-02-21
4e9fc0e Update 2022-02-20
75bf364 Update 2022-02-19
ce1a8a4 (tag: 2022-02-18) Update 2022-02-18
```

**Comment by rgerhards** [comment]
Nachtrag: ich habe zu flüchtig gelesen, #18 war ja schon erwähnt!

Wenn möglich, wäre es gut zumindest die tags der letzten 30 Tage zu ergänzen, SOFERN das vollständige Aktualisierungen waren. Ich hatte nach analyse der commits selbst den Eindruck, dass das der Fall ist. Leider kann man tags  nicht in einen PR packen, sonst hätte ich das schon gemacht.

Aber wenn es zu viel Arbeit ist: dann natürlich nicht, in der Situation verständlich (wenn auch schade). Prima ist, dass bei Meldung die aktuellen tags nachgeholt werden. Das ist schon mal was :-)

**Comment by HannesWuensche** [comment]
Hallo @rgerhards,

wir haben die Fehlen Tags für die Commits:

```
4e9fc0e Update 2022-02-20
75bf364 Update 2022-02-19
```
hinzugefügt. Auch in einigen früheren Commits wo Tags fehlten sind diese nun ergänzt. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by rgerhards** [comment]
Herzlichen Dank!
