### ISSUE TITLE
tag 2022-03-03 is missing

### ISSUE THREAD

**Issue by rgerhards** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#18]
f96985b (HEAD -> master, origin/master, origin/HEAD) Update 2022-03-03
2228947 Update 2022-03-03
d09f6f0 Update 2022-03-02
37cdc2a (tag: 2022-03-02) Update 2022-03-02
b443233 (tag: 2022-03-01) Update 2022-03-01
bdd7ea4 (tag: 2022-02-28) Update 2022-02-28
3e008f9 Update 2022-03-01

**Comment by HannesWuensche** [comment]
Hallo @rgerhards,

danke für den Hinweis. Wie alle derzeit mitbekommen, haben wir Probleme mit der Zuverlässigkeit der Pipeline. 
Daher kommt es leider zu Unregelmäßigkeiten. Der Datenstand ist jetzt getagged. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
