### ISSUE TITLE
Zuordnung zwischen IMS_ID und GISAID Accession

### ISSUE THREAD

**Issue by lenaschimmel** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#21]
Sequenzen bei GISAID werden über ihren "Virus name" (z.B. `Germany/NW-RKI-I-592489/2022`) und ihre Accession (z.B. `EPI_ISL_10910370`) identifiziert, während sie in diesem Datensatz eine IMS_ID wie z.B. `IMS-10294-CVDP-48D4B4C1-58D3-4C97-A368-7EBB8E5D1989` haben.

Ich sehe derzeit keinen Weg, wie die verschiedenen IDs derselben Sequenz einander zugeordnet werden können, was die Kommunikation zwischen Wissenschafter_innen, die primär auf den RKI-Daten arbeiten, und denen, die auf den globalen GISAID-Daten arbeiten, erschwert.

Da es für mich nicht so aussieht, als würden die IDs nach einem einfachen (mathematischen) Prinzip auseinander abgeleitet werden, müsste vermutlich in der `SARS-CoV-2-Sequenzdaten_Deutschland.csv(.xz)` eine bzw. zwei weitere Spalte(n) eingeführt werden, in der die GISAID ID(s) nachgetragen werden, sobald die Sequenzen auch dort verfügbar sind?

**Comment by cuehs** [comment]
@lenaschimmel 
Genau das haben wir bereits auf der Roadmap. 

Es ist auch möglich bei GISAID nach der IMS_ID zu filtern:

![image](https://user-images.githubusercontent.com/2464278/158341594-47799d10-3c93-446e-9973-1afa69b6343e.png)
Activate “sample ID given by the  originating lab”
![image](https://user-images.githubusercontent.com/2464278/158341623-6c3ef0d7-a6a7-4866-8ea6-aed8a88a59f3.png)

**Comment by lenaschimmel** [comment]
> @lenaschimmel Genau das haben wir bereits auf der Roadmap.

Das ist super!

> Als workaround ist auch möglich bei GISAID nach der IMS_ID zu filtern:

Das heißt, für Personen mit GISAID-Zugang funktioniert dieser Workaround auch umgekehrt? Also, bei bekannter Accession kann in GISAID die IMS_ID angezeigt werden?

_(Kann es derzeit nicht selbst prüfen, da ich noch auf Freischaltung meines GISAID-Accounts warte.)_

**Comment by cuehs** [comment]
> Das heißt, für Personen mit GISAID-Zugang funktioniert dieser Workaround auch umgekehrt? Also, bei bekannter Accession kann in GISAID die IMS_ID angezeigt werden?

Genau. Eine Person kann bei in GISAID bei einer Sequenz aus dem RKI prüfen welche IMS_ID dafür vorhanden ist.

**Comment by cuehs** [comment]
Die Spalte GISAID_ACCESSION wurde hinzugefügt
