### ISSUE TITLE
Last update to ENA/Genbank seems to have been 6 weeks ago

### ISSUE THREAD

**Issue by corneliusroemer** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#22]
I've noticed that the last update to ENA/Genbank seems to have been about 6 weeks ago. Before then, you seem to have uploaded regularly to ENA. Is this on purpose?

It's a big advantage to have German sequences available freely. That way, they can appear in open.cov-spectrum.org for example, which allows for a nice integration with Nextclade.

For sequences that are available through GISAID only, that's unfortuantely not possible.

Thanks for your work!

**Comment by cuehs** [comment]
@corneliusroemer 
We are planing to continue the ENA publication process soon (ETA is early next week).

**Comment by corneliusroemer** [comment]
Fab, thanks! Much appreciated.

Having sequences out in the open enables tools that would otherwise not be possible.
