### ISSUE TITLE
Fehlende Updates der SARS-CoV-2-Entwicklungslinien_Deutschland.csv.xz

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#23]
Hallo,

Zur Info:
Gestern und heute morgen gab es keine Updates mehr für die Entwicklungslinien CSV.

Viele Grüße
David

**Comment by HannesWuensche** [comment]
Hallo @icestorm972,

die Daten von gestern sind leider erst sehr spät gekommen. Die Pipeline scheint derzeit etwas zu hängen. 
Auch die heutigen Daten sind noch nicht enthalten, wir versuchen schnellstmöglich die Stabilität der Veröffentlichungen wieder herzustellen. 

Beste Grüße
@HannesWuensche 
für das Team RKI | Open Data

**Comment by icestorm972** [comment]
Zur Info:
Heute morgen hing die Pipeline wohl wieder.
