### ISSUE TITLE
Updates fehlen/Pipeline scheint zu hängen

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#24]
Guten Morgen,

es scheint wieder ein Problem mit der Pipeline zu bestehen:
* Gestern morgen wurde nur die ".zenodo.json" aktualisiert, aber die "SARS-CoV-2-Entwicklungslinien_Deutschland.csv.xz" nicht
* Das Update der "SARS-CoV-2-Sequenzdaten_Deutschland.*.xz" nach 22 Uhr fiel auch aus
* Heute morgen bisher auch kein Update

Viele Grüße
David

**Comment by HannesWuensche** [comment]
Hallo @icestorm972,

wenn nur die .zenodo.json aktualisiert wird, dann gab es keine Differenz zu den Entwicklungslinien des Vortags. In dem Fall also kein Problem in der Pipeline. 

Gestern Abend gab es keine neuen Sequenzdaten richtig. wir hoffen das es heute Abend wieder läuft. 

Beste Grüße
@HannesWuensche 
für das Team RKI | Open Data
