### ISSUE TITLE
Fehlklassifizierungen von BA.4/5 Sequenzen durch Scorpio als "BA.2-like" führt zu vielen "Unassigned" oder "BA.2" Zuweisungen

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#25]
Hi,

zur Info: 
Viele BA.5 Sequenzen werden seit einer Weile von Scorpio nicht mehr erkannt und als *Omicron (BA.2-like)* eingestuft<sup>*)</sup>  das in der **SARS-CoV-2-Entwicklungslinien_Deutschland.csv.xz** zu *Unassigned* oder *BA.2* Klassifizierungen führt.

Siehe auch
* [Pango-Designation Issue #599: "Scorpio: Many BA.4/5 misclassified as BA.2* because "Probable Omicron (BA.2-like)"](https://github.com/cov-lineages/pango-designation/issues/599)
* [Tweet Cornelius Römer: "Beware when you look at BA.4/5 proportions that are based on Pango lineages as returned by pangoLEARN (i.e. GISAID): for some countries, a large proportion of true BA.4/5 are misclassified as BA.2..."](https://mobile.twitter.com/CorneliusRoemer/status/1534222459448197121?t=Hmiepu2nC9k_XPizcE3q_A)

Als Workaround (bis das Problem beseitigt ist) wird zu "--skip-scorpio"  geraten.

<sup>*)</sup> Auch ersichtlich durch die vielen note Einträge ala "BA.5(2/2); scorpio replaced lineage inference BA.5"

Viele Grüße
David

**Comment by HannesWuensche** [comment]
Hallo @icestorm972,

vielen Dank für den Hinweis. 
Nach Rücksprache mit den Kolleg:innen kann ich folgende Rückmeldungen geben:

Um das Problem zu umgehen, werden wir in naher Zukunft Scorpio nicht mehr nutzen. Derzeitig sind wir noch dabei  die neue Zuordnungsstrategie zu testen und zu evaluieren. Geplant ist, dass sich die Linienzuordnungen so "von allein" heilen und nur noch die Usherzuordnung genutzt werden. 

Mit besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data

**Comment by icestorm972** [comment]
Super :-)

Wenn ich das richtig gesehen habe, ist das jetzt live?

Btw, seit Samstag gab es keine neuen Sequenzen mehr?

**Comment by HannesWuensche** [comment]
Hallo @icestorm972,

ich habe des Thema in #26 aufgenommen.

Beste Grüße
@HannesWuensche 
für das Team RKI | Open Data
