### ISSUE TITLE
Fehlende Sequenzdaten csv/fasta Uploads ab "Update 2022-07-25"

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#29]
Guten Morgen,

kann es sein, dass es wieder Pipeline-Probleme gibt?
Der letzte Commit mit "SARS-CoV-2-Sequenzdaten_Deutschland.csv.xz" & "SARS-CoV-2-Sequenzdaten_Deutschland.fasta.xz" (plus zugehöriger ".zenodo.json") war am 24. Juli.

Viele Grüße,
David

**Comment by RKIOpenData** [comment]
Hallo David,

danke für den Hinweis. Ja, das ist leider korrekt. Wir arbeiten gerade an einer Lösung. Ich gebe hier Bescheid sobald alles wieder funktioniert

viele Grüße
Knut Perseke
für das Team Open Data RKI

**Comment by RKIOpenData** [comment]
Hi David,

wir konnten das Problem lösen und die Daten wurden heute Nacht wieder hochgeladen. Deshalb schließe ich das Ticket. Falls es noch Probleme geben sollte mache es aber gern wieder auf

viele Grüße
Knut Perseke
für das Team Open Data RKI

**Comment by icestorm972** [comment]
Zur Info:
Gestern und heute abend (21:30+) kam kein Update-Lauf für
"SARS-CoV-2-Sequenzdaten_Deutschland.csv.xz", "SARS-CoV-2-Sequenzdaten_Deutschland.fasta.xz" und ".zenodo.json"
