### ISSUE TITLE
Very diverse set of sequences with S:P348H (almost exclusive to Germany) in just two submission dates

### ISSUE THREAD

**Issue by corneliusroemer** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#30]
I noticed that there are ~222 sequences from Germany with S:P384H that come from a big range of lineages suggesting the mutation is an artefact.

<img width="2523" alt="image" src="https://user-images.githubusercontent.com/25161793/184171657-e25df02a-1846-41de-ab35-23a44b357428.png">

<img width="2532" alt="image" src="https://user-images.githubusercontent.com/25161793/184171674-87c223d5-4f22-4867-a775-8895e2278687.png">

Maybe this is a similar issue as in #27 

Could you check with the lab what's going on there?

See where they lie on the tree - these are all the German ones, this mutation is basically non-existent outside of Germany

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/25161793/184171619-89406dd0-1e25-4e35-bd82-242e07fde22f.png">

These are the EPI_ISLs:
EPI_ISL_13241333
EPI_ISL_13241331
EPI_ISL_13944767
EPI_ISL_13241276
EPI_ISL_13241242
EPI_ISL_13944809
EPI_ISL_13241312
EPI_ISL_13944771
EPI_ISL_13944776
EPI_ISL_13241342
EPI_ISL_13944821
EPI_ISL_10294132
EPI_ISL_13241290
EPI_ISL_13944834
EPI_ISL_13944779
EPI_ISL_13241340
EPI_ISL_13944783
EPI_ISL_13241292
EPI_ISL_13241246
EPI_ISL_13241341
EPI_ISL_13944869
EPI_ISL_13241300
EPI_ISL_13944848
EPI_ISL_13241317
EPI_ISL_13241235
EPI_ISL_13944770
EPI_ISL_13241250
EPI_ISL_13241278
EPI_ISL_13241316
EPI_ISL_13241238
EPI_ISL_13241263
EPI_ISL_13241282
EPI_ISL_13241308
EPI_ISL_13241293
EPI_ISL_13944860
EPI_ISL_13944831
EPI_ISL_13241335
EPI_ISL_13944766
EPI_ISL_13241343
EPI_ISL_13944850
EPI_ISL_13241320
EPI_ISL_13241251
EPI_ISL_13944852
EPI_ISL_13944777
EPI_ISL_13241277
EPI_ISL_13241249
EPI_ISL_13241306
EPI_ISL_13241241
EPI_ISL_13241243
EPI_ISL_13241280
EPI_ISL_13944801
EPI_ISL_13241301
EPI_ISL_13944790
EPI_ISL_13944763
EPI_ISL_13944827
EPI_ISL_13944780
EPI_ISL_13944810
EPI_ISL_13944846
EPI_ISL_13241304
EPI_ISL_13241267
EPI_ISL_13944817
EPI_ISL_13944798
EPI_ISL_13944761
EPI_ISL_13241314
EPI_ISL_13241330
EPI_ISL_13944858
EPI_ISL_13944781
EPI_ISL_13944833
EPI_ISL_13241272
EPI_ISL_13241337
EPI_ISL_13241311
EPI_ISL_13241237
EPI_ISL_13241328
EPI_ISL_13241295
EPI_ISL_13944760
EPI_ISL_13944864
EPI_ISL_13241285
EPI_ISL_13944842
EPI_ISL_13944868
EPI_ISL_13944857
EPI_ISL_13241299
EPI_ISL_13944775
EPI_ISL_13241296
EPI_ISL_13944786
EPI_ISL_13944870
EPI_ISL_13241255
EPI_ISL_13944820
EPI_ISL_13944862
EPI_ISL_13944859
EPI_ISL_13241288
EPI_ISL_13944806
EPI_ISL_13241307
EPI_ISL_13241309
EPI_ISL_13944815
EPI_ISL_13241303
EPI_ISL_13241271
EPI_ISL_13241240
EPI_ISL_13944819
EPI_ISL_13944813
EPI_ISL_13944808
EPI_ISL_13241268
EPI_ISL_13944836
EPI_ISL_13241279
EPI_ISL_13944797
EPI_ISL_13241325
EPI_ISL_13944778
EPI_ISL_13944824
EPI_ISL_13944789
EPI_ISL_13944832
EPI_ISL_13241245
EPI_ISL_13944818
EPI_ISL_13944782
EPI_ISL_13241318
EPI_ISL_13944849
EPI_ISL_13944765
EPI_ISL_13944773
EPI_ISL_13241344
EPI_ISL_13944843
EPI_ISL_13241291
EPI_ISL_13944811
EPI_ISL_13241259
EPI_ISL_13944768
EPI_ISL_13944826
EPI_ISL_13944867
EPI_ISL_13944787
EPI_ISL_13241256
EPI_ISL_13241338
EPI_ISL_13944794
EPI_ISL_13944796
EPI_ISL_13241287
EPI_ISL_13944769
EPI_ISL_13944855
EPI_ISL_13241322
EPI_ISL_13241305
EPI_ISL_13241258
EPI_ISL_13241332
EPI_ISL_13241254
EPI_ISL_13241324
EPI_ISL_13241262
EPI_ISL_13944830
EPI_ISL_13944800
EPI_ISL_13944799
EPI_ISL_13944784
EPI_ISL_13944841
EPI_ISL_13241244
EPI_ISL_13944828
EPI_ISL_13944838
EPI_ISL_13944861
EPI_ISL_13241265
EPI_ISL_13944793
EPI_ISL_13944792
EPI_ISL_13241286
EPI_ISL_13241270
EPI_ISL_13241239
EPI_ISL_13241323
EPI_ISL_13241315
EPI_ISL_13241253
EPI_ISL_13944844
EPI_ISL_13944863
EPI_ISL_13944772
EPI_ISL_13944866
EPI_ISL_13241302
EPI_ISL_13241329
EPI_ISL_13944854
EPI_ISL_13241298
EPI_ISL_13241247
EPI_ISL_13241284
EPI_ISL_13944795
EPI_ISL_13944871
EPI_ISL_13944839
EPI_ISL_13944823
EPI_ISL_13241260
EPI_ISL_13944802
EPI_ISL_13944805
EPI_ISL_13944812
EPI_ISL_13944788
EPI_ISL_13944865
EPI_ISL_13241319
EPI_ISL_13241289
EPI_ISL_13241339
EPI_ISL_13944785
EPI_ISL_13241266
EPI_ISL_13944853
EPI_ISL_13944764
EPI_ISL_13241283
EPI_ISL_13241313
EPI_ISL_13241248
EPI_ISL_13944816
EPI_ISL_13241236
EPI_ISL_13944825
EPI_ISL_13944856
EPI_ISL_13944847
EPI_ISL_13944814
EPI_ISL_13241264
EPI_ISL_13241334
EPI_ISL_13944845
EPI_ISL_13241257
EPI_ISL_13241327
EPI_ISL_13241273
EPI_ISL_13241297
EPI_ISL_13944829
EPI_ISL_13241281
EPI_ISL_13944804
EPI_ISL_13241310
EPI_ISL_13944791
EPI_ISL_13944837
EPI_ISL_13241275
EPI_ISL_13944807
EPI_ISL_13944840
EPI_ISL_13241336
EPI_ISL_13944835
EPI_ISL_13241261
EPI_ISL_13241321
EPI_ISL_13944762
EPI_ISL_13944851
EPI_ISL_13944774
EPI_ISL_13944803
EPI_ISL_13944822
EPI_ISL_13241274
EPI_ISL_13241294
EPI_ISL_13241252
EPI_ISL_13241326

**Comment by MarieLataretu** [comment]
Hi @corneliusroemer ,
many thanks for reporting this!

Looking at the DESH data, it is most probably a (sequencing) lab bias. 
We are in contact with the lab.
