### ISSUE TITLE
Update pangolin-data to v1.13 (it's at v1.12 right now)

### ISSUE THREAD

**Issue by corneliusroemer** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#31]
It would be great if you could update pangolin-data to the latest version, it's running at v1.12 right now but v1.13 has been out for more than a week now.

This is the current pangolin output in this repo, note the v1.12
<img width="1718" alt="image" src="https://user-images.githubusercontent.com/25161793/185368131-6660d119-e5a1-4ec8-9f2f-bbf8641ecd90.png">

These are the lineages you're missing, as they were released in v1.13
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/25161793/185368179-83ca84a1-55e2-4d73-b002-a32b8eb7d4a8.png">

Here's the release:
https://github.com/cov-lineages/pangolin-data/releases/tag/v1.13

**Comment by mg14** [comment]
This seems relevant as BF.7 (and other BA.5* variants with S:346T) seem to be rising, but are missed by v.1.12: 
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/6615711/185369467-443e0c06-8f8f-4f1d-97de-50d87f47b680.png">
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/6615711/185369747-6bcbf2ed-84a1-4ae1-b259-c273790c0803.png">

**Comment by matthuska** [comment]
Hi @corneliusroemer , we use the conda packages for pangolin and its dependencies. Currently the current conda package for pangolin-data says it is 1.13, but pangolin --all-versions reports 1.12:

```
$ conda list | grep pangolin-data
pangolin                  4.1.2              pyhdfd78af_0    bioconda
pangolin-data             1.13               pyh5e36f6f_0    bioconda
$ pangolin --all-versions
pangolin: 4.1.2
pangolin-data: 1.12
constellations: v0.1.10
scorpio: 0.3.17
usher 0.5.4
gofasta 1.1.0
minimap2 2.24-r1122
faToVcf: 426
```

This is a known issue and has been reported to the pangolin-data issue tracker: https://github.com/cov-lineages/pangolin-data/issues/22#issuecomment-1214759528

As soon as that is resolved and an updated conda package for pangolin-data is released we will automatically start using it.

**Comment by mg14** [comment]
Hi Matt I think this is fixed now, see

https://github.com/cov-lineages/pangolin-data/issues/22#issuecomment-1220661321

**Comment by corneliusroemer** [comment]
Thanks @matthuska for explaining!

I think for the future: you can update the data yourself simply by running `pangolin --update-data` - not relying on bioconda to update the data first.

**Comment by matthuska** [comment]
Thanks @corneliusroemer , there are some technical reasons why we have to stick to conda for all updates. It can lead to delayed updates but we have some internal processes that require us to be able to exactly recreate older pangolin environments, and for that we rely on conda. Thanks for your patience.

**Comment by mg14** [comment]
Hi Matt - problem solved, thanks!

https://mobile.twitter.com/MoritzGerstung/status/1560864142952730624
