### ISSUE TITLE
Potential sequencing error:  S:Q1054E showing up in just Germany on all sorts of lineages

### ISSUE THREAD

**Issue by corneliusroemer** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#32]
Looking at recent German sequences, I noticed that S:Q1054E has suddenly popped up all over the tree - not just in one but in all sorts of lineages.

It has also never appeared outside of Germany. That's very indicative of a sequencing error / artefact.

Could you check with the lab? That'd be great

Unfortunately it appears that the actual lab doing the sequencing is not provided in the GISAID metadata - it seems that the originating lab is the lab that did the PCR not the lab that did the sequencing.

It may be more useful to have the lab that did the sequencing listed there - as in this case there are a handful of labs with this error - but I strongly suspect it's in fact only one lab that did the sequencing for all the submitters.

For the large amount of money German labs get for each sequence (is it still >200 EUR) one should expect good quality and no errors like this that should easily be identified if the sequencing lab ran their sequences through e.g. Nextclade.

This issue is similar to #27 #30

Here's a covSpectrum query: 
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AQ1054E&

These are EPI_ISLs:
EPI_ISL_14432551
EPI_ISL_14414119
EPI_ISL_14432663
EPI_ISL_14520784
EPI_ISL_14414320
EPI_ISL_14408625
EPI_ISL_14367877
EPI_ISL_14367902
EPI_ISL_14520547
EPI_ISL_14402843
EPI_ISL_14432225
EPI_ISL_14520809
EPI_ISL_14378924
EPI_ISL_13945683
EPI_ISL_14408267
EPI_ISL_14520827
EPI_ISL_14432063
EPI_ISL_13921602
EPI_ISL_14432642
EPI_ISL_14520545
EPI_ISL_14416139
EPI_ISL_14367888
EPI_ISL_14520746
EPI_ISL_14520772
EPI_ISL_13921663
EPI_ISL_14432249
EPI_ISL_14520757
EPI_ISL_14408704
EPI_ISL_13946392
EPI_ISL_13921585
EPI_ISL_14415977
EPI_ISL_14415045
EPI_ISL_14408443
EPI_ISL_13921433
EPI_ISL_14416174
EPI_ISL_14520697
EPI_ISL_14520665
EPI_ISL_14520885
EPI_ISL_14379121
EPI_ISL_14378915
EPI_ISL_14409100
EPI_ISL_14403138
EPI_ISL_13921644
EPI_ISL_14432584
EPI_ISL_14432580
EPI_ISL_14379009
EPI_ISL_14432590
EPI_ISL_14432684
EPI_ISL_13921591
EPI_ISL_14520666
EPI_ISL_14520922
EPI_ISL_14432325
EPI_ISL_13921819
EPI_ISL_14520852
EPI_ISL_14379110
EPI_ISL_14398549
EPI_ISL_14521363
EPI_ISL_14432662
EPI_ISL_14432546
EPI_ISL_14403055
EPI_ISL_14520995
EPI_ISL_14520695
EPI_ISL_14367770
EPI_ISL_14367986
EPI_ISL_14402716
EPI_ISL_14414415
EPI_ISL_14379012
EPI_ISL_14520517
EPI_ISL_14521016
EPI_ISL_14409031
EPI_ISL_14379015
EPI_ISL_14407921
EPI_ISL_14402891
EPI_ISL_14520905
EPI_ISL_14395507
EPI_ISL_14432162
EPI_ISL_14520751
EPI_ISL_14415985
EPI_ISL_14414742
EPI_ISL_14432634
EPI_ISL_14408455
EPI_ISL_14416181
EPI_ISL_14379207
EPI_ISL_14409109
EPI_ISL_14432688
EPI_ISL_14416249
EPI_ISL_13946281
EPI_ISL_14395504
EPI_ISL_14432613
EPI_ISL_14367878
EPI_ISL_14432257
EPI_ISL_14432310
EPI_ISL_14432534
EPI_ISL_14520561
EPI_ISL_13942426
EPI_ISL_14520918
EPI_ISL_14415940
EPI_ISL_14520834
EPI_ISL_13945685
EPI_ISL_14432630
EPI_ISL_14432184
EPI_ISL_14413973
EPI_ISL_14368232
EPI_ISL_14416216
EPI_ISL_13936037
EPI_ISL_13946427
EPI_ISL_14520926
EPI_ISL_14415733
EPI_ISL_14432576
EPI_ISL_14520720
EPI_ISL_14402345
EPI_ISL_14520768
EPI_ISL_14521133
EPI_ISL_14367803
EPI_ISL_14414821
EPI_ISL_14414254
EPI_ISL_13946390
EPI_ISL_14432658
EPI_ISL_14432552
EPI_ISL_14415944
EPI_ISL_14520851
EPI_ISL_13942371
EPI_ISL_14378986
EPI_ISL_14432635
EPI_ISL_14432449
EPI_ISL_14414390
EPI_ISL_13921310
EPI_ISL_14367662
EPI_ISL_13945843
EPI_ISL_14414940
EPI_ISL_14378983
EPI_ISL_14379135
EPI_ISL_14432531
EPI_ISL_14379142
EPI_ISL_14521169
EPI_ISL_14432618
EPI_ISL_14432665
EPI_ISL_14414321
EPI_ISL_14432255
EPI_ISL_14432562
EPI_ISL_14408562
EPI_ISL_13946435
EPI_ISL_14520753
EPI_ISL_14408615
EPI_ISL_14379021
EPI_ISL_13935996
EPI_ISL_13921631
EPI_ISL_14408824
EPI_ISL_14367983
EPI_ISL_14379019
EPI_ISL_14408468
EPI_ISL_13921641
EPI_ISL_14367753
EPI_ISL_14408658
EPI_ISL_14432294
EPI_ISL_14520807
EPI_ISL_14379162
EPI_ISL_14432636
EPI_ISL_14379076
EPI_ISL_14520657
EPI_ISL_14520850
EPI_ISL_14520715
EPI_ISL_14432647
EPI_ISL_14402383
EPI_ISL_14432573
EPI_ISL_14520701
EPI_ISL_14432489
EPI_ISL_14520536
EPI_ISL_14379061
EPI_ISL_14520719
EPI_ISL_14415402
EPI_ISL_13935999
EPI_ISL_14379118
EPI_ISL_14378987
EPI_ISL_14395460
EPI_ISL_14432461
EPI_ISL_13921686
EPI_ISL_14415861
EPI_ISL_14432664
EPI_ISL_14408469
EPI_ISL_14379069
EPI_ISL_13942286
EPI_ISL_14408701
EPI_ISL_14432351
EPI_ISL_13942085
EPI_ISL_14432416
EPI_ISL_14408921
EPI_ISL_14408440
EPI_ISL_14378944
EPI_ISL_14520766
EPI_ISL_13941967
EPI_ISL_14520869
EPI_ISL_14432569
EPI_ISL_14398631
EPI_ISL_14379068
EPI_ISL_14520659
EPI_ISL_14402886
EPI_ISL_14520788
EPI_ISL_14432446
EPI_ISL_14408661
EPI_ISL_14379130
EPI_ISL_14367875
EPI_ISL_14408138
EPI_ISL_14408174
EPI_ISL_14367735
EPI_ISL_14398360
EPI_ISL_13936051
EPI_ISL_13921518
EPI_ISL_14408300
EPI_ISL_14416113
EPI_ISL_14413999
EPI_ISL_14432570
EPI_ISL_14432440
EPI_ISL_14416211
EPI_ISL_14403051
EPI_ISL_14407946
EPI_ISL_14379050
EPI_ISL_14408302
EPI_ISL_14520676
EPI_ISL_14520765
EPI_ISL_13945660
EPI_ISL_14402214
EPI_ISL_14520762
EPI_ISL_14432648
EPI_ISL_13945867
EPI_ISL_13921776
EPI_ISL_14414238
EPI_ISL_14520813
EPI_ISL_14415936
EPI_ISL_14367957
EPI_ISL_14521595
EPI_ISL_14415947
EPI_ISL_14520868
EPI_ISL_14520823
EPI_ISL_14415034
EPI_ISL_14432652
EPI_ISL_14416069
EPI_ISL_14402852
EPI_ISL_14408384
EPI_ISL_14414606
EPI_ISL_14402953
EPI_ISL_14520781
EPI_ISL_14408914
EPI_ISL_14408402
EPI_ISL_14408359
EPI_ISL_14408213
EPI_ISL_14408631
EPI_ISL_13921612
EPI_ISL_14416185
EPI_ISL_14408295
EPI_ISL_14432568
EPI_ISL_14408628
EPI_ISL_14403002
EPI_ISL_13921464
EPI_ISL_14407937
EPI_ISL_14520906
EPI_ISL_14395980
EPI_ISL_14414945
EPI_ISL_14408618
EPI_ISL_14415660
EPI_ISL_14402616
EPI_ISL_13946508
EPI_ISL_14432418
EPI_ISL_14432285
EPI_ISL_14432176
EPI_ISL_14432448
EPI_ISL_14401772
EPI_ISL_14402845
EPI_ISL_14408268
EPI_ISL_14408348
EPI_ISL_14414400
EPI_ISL_13942405
EPI_ISL_14520692
EPI_ISL_14432082
EPI_ISL_14379056
EPI_ISL_14367742
EPI_ISL_14520806
EPI_ISL_14432213
EPI_ISL_14408133
EPI_ISL_14416175
EPI_ISL_14379036
EPI_ISL_14432393
EPI_ISL_14414732
EPI_ISL_14432686
EPI_ISL_13922240
EPI_ISL_14408362
EPI_ISL_14432343
EPI_ISL_14408650
EPI_ISL_14401755
EPI_ISL_14520528
EPI_ISL_14402998
EPI_ISL_14402297
EPI_ISL_14521095
EPI_ISL_14379077
EPI_ISL_14402222
EPI_ISL_14367757
EPI_ISL_14520522
EPI_ISL_14416228
EPI_ISL_13945808
EPI_ISL_14409039
EPI_ISL_13921637
EPI_ISL_14520544
EPI_ISL_14415088
EPI_ISL_13921646
EPI_ISL_14395040
EPI_ISL_14402688
EPI_ISL_14432091
EPI_ISL_13921554
EPI_ISL_14432471
EPI_ISL_13921825
EPI_ISL_14520748
EPI_ISL_14520726
EPI_ISL_14408835
EPI_ISL_14379140
EPI_ISL_14408698
EPI_ISL_13946474
EPI_ISL_14367646
EPI_ISL_14409154
EPI_ISL_14408575
EPI_ISL_14367754
EPI_ISL_14432593
EPI_ISL_14367681
EPI_ISL_14408676
EPI_ISL_14367873
EPI_ISL_14520760
EPI_ISL_13945886
EPI_ISL_14520898
EPI_ISL_14398192
EPI_ISL_14414215
EPI_ISL_14367713
EPI_ISL_14379072
EPI_ISL_14395860
EPI_ISL_13936179
EPI_ISL_14379101
EPI_ISL_13945715
EPI_ISL_14408696
EPI_ISL_14432317
EPI_ISL_14378958
EPI_ISL_14432693
EPI_ISL_14402968
EPI_ISL_14378891
EPI_ISL_14408655
EPI_ISL_14408369
EPI_ISL_14408866
EPI_ISL_13921565
EPI_ISL_14432510
EPI_ISL_13945842
EPI_ISL_14378996
EPI_ISL_14415642
EPI_ISL_14521253
EPI_ISL_14408274
EPI_ISL_14408132
EPI_ISL_14398234
EPI_ISL_14402940
EPI_ISL_14367764
EPI_ISL_14413981
EPI_ISL_14414334
EPI_ISL_14414843
EPI_ISL_14402878
EPI_ISL_14521102
EPI_ISL_14520824
EPI_ISL_14432521
EPI_ISL_14432425
EPI_ISL_14432453
EPI_ISL_14432695
EPI_ISL_14379043
EPI_ISL_14520538
EPI_ISL_14402725
EPI_ISL_14379073
EPI_ISL_13921584
EPI_ISL_14520840
EPI_ISL_14401992
EPI_ISL_14432560
EPI_ISL_14520754
EPI_ISL_14402613
EPI_ISL_14520796
EPI_ISL_14432683
EPI_ISL_14432666
EPI_ISL_13945723
EPI_ISL_13945664
EPI_ISL_14432604
EPI_ISL_14432256
EPI_ISL_14408897
EPI_ISL_13946332
EPI_ISL_14416027
EPI_ISL_14432639
EPI_ISL_14403079
EPI_ISL_14408684
EPI_ISL_14379198
EPI_ISL_14520888

**Comment by MarieLataretu** [comment]
Hi @corneliusroemer ,
thanks again for reporting!

Here, it also looks like a (sequencing) lab bias in the DESH data. 
We are in contact with the lab.
