### ISSUE TITLE
Fehlende Sequenzdaten (csv/fasta) Uploads ab 2022-08-31

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#34]
Guten Morgen,

Zur Info, es scheint wieder Pipeline-Probleme im Nachtlauf (Sequenzen, ~21:30) zu geben.

Der letzte Commit mit "SARS-CoV-2-Sequenzdaten_Deutschland.csv.xz", "SARS-CoV-2-Sequenzdaten_Deutschland.fasta.xz" (plus zugehöriger ".zenodo.json") war am 30. August.

Viele Grüße,
David

Siehe auch
https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/issues/29

**Comment by cuehs** [comment]
Hi @icestorm972 das Problem ist uns bekannt und wir versuchen es so schnell wie möglich zu beheben.

**Comment by icestorm972** [comment]
Es kommen zwar wieder Updates mit ein paar 100 Sequenzdaten, aber es scheinen viele Sequenzdaten seit 31.08. zu fehlen?
![Figure 2022-09-05 072115](https://user-images.githubusercontent.com/20755156/188366195-e5c3048b-115b-431b-b197-54a8ebc30930.png)

**Comment by cuehs** [comment]
Die fehlenden Sequenzen sollten heute Abend verarbeitet und bereitgestellt werden.

**Comment by icestorm972** [comment]
![Figure 2022-09-08 073526](https://user-images.githubusercontent.com/20755156/189060719-acf01059-518d-46a4-8f21-36f3682fdcb3.png)
Das Update heute Nacht sah gut aus bzgl Nachmeldungen der Ausfälle letzter Woche und von vorgestern 😊

**Comment by cuehs** [comment]
Dann mach ich mal zu.
