### ISSUE TITLE
Fehlende Sequenzdaten (csv/fasta) Uploads ab 2022-09-19

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#36]
Hi,

zur Info:
seit 2 Tagen gibt es nachts keine SARS-CoV-2-Sequenzdaten_Deutschland.fasta.xz / *.csv.xz Uploads mehr (auch kein zenodo Metadata, analog https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/issues/34).

Viele Grüße
David

P.S.
Hat der Fix von https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/issues/35 vielleicht damit was zu tun, oder nur zufällig zeitgleich?

**Comment by cuehs** [comment]
@cuehs

**Comment by HannesWuensche** [comment]
Hallo @icestorm972,

wir haben gerade die Sequenzdaten von gestern bereitgestellt. 
Wir hoffen alle Fehler sind beseitigt und ab heute Abend alle Datenbereitstellungen wieder in der gewohnten Regelmäßigkeit. 
Allgemein: Beide Pipelines greifen auf die gleichen Rohdaten zu, arbeiten aber insgesamt unabhängig voneinander. 

Mit besten Grüße
@HannesWuensche 
für das Team RKI | Open Data

**Comment by icestorm972** [comment]
Alles klar, Danke! 😊
