### ISSUE TITLE
Potentially misdated sequences from Berlin uploaded to GISAID by RKI today 

### ISSUE THREAD

**Issue by corneliusroemer** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#37]
In today's uploads from RKI, I noticed some Delta sequences with collection date just a week ago that have far too few mutations.

It appears that the collection date is incorrect - one would not find a Delta with 40 mutations today, unless it was in the freezer for a year, since every year around 30 mutations are acquired no matter what.

It appears that the originating lab for these Deltas is
```
Originating lab: | Robert Koch-Institut ZBS1 (Zentrum für biologische Gefahren und spezielle Pathogene hochpathogene Viren)
```

Could you check with the lab to see whether they got the year wrong? 2022 instead of 2021?

Here are some sample sequences to look into (some of them are BA.1 - but similarly underdiverged for the stated collection date).

If the precise collection date is not known, it's better to put it as 2021 instead of giving it a precise but wrong date.

```
hCoV-19/Germany/BE-RKI-I-984654/2022|EPI_ISL_15148193|2022-09-20
hCoV-19/Germany/BE-RKI-I-984662/2022|EPI_ISL_15148201|2022-09-20
hCoV-19/Germany/BE-RKI-I-984666/2022|EPI_ISL_15148205|2022-09-20
hCoV-19/Germany/BE-RKI-I-984662/2022|EPI_ISL_15148201|2022-09-20
hCoV-19/Germany/BE-RKI-I-984659/2022|EPI_ISL_15148198|2022-09-20
hCoV-19/Germany/BE-RKI-I-984655/2022|EPI_ISL_15148194|2022-09-20
hCoV-19/Germany/BE-RKI-I-984653/2022|EPI_ISL_15148192|2022-09-20
hCoV-19/Germany/BE-RKI-I-984639/2022|EPI_ISL_15148179|2022-09-20
hCoV-19/Germany/BE-RKI-I-984636/2022|EPI_ISL_15148176|2022-09-20
hCoV-19/Germany/BE-RKI-I-984667/2022|EPI_ISL_15148206|2022-09-20
hCoV-19/Germany/BE-RKI-I-984664/2022|EPI_ISL_15148203|2022-09-20
hCoV-19/Germany/BE-RKI-I-984660/2022|EPI_ISL_15148199|2022-09-20
hCoV-19/Germany/BE-RKI-I-984658/2022|EPI_ISL_15148197|2022-09-20
```

**Comment by akifoss** [comment]
Hey, this issue has been taken care of and the dates for the above genomes are corrected. These were indeed genomes sequenced in 2021 or early 2022
