### ISSUE TITLE
Fehlende Sequenz-/Metadaten (csv/fasta) Uploads ab 2022-09-27

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#38]
Hi,

zur Info:
Letztes erfolgreiches Update war am Montag, den 26.09., seitdem gab es nachts/abends keine SARS-CoV-2-Sequenzdaten_Deutschland.fasta.xz bzw .csv.xz Uploads mehr (auch keine zugehörige zenodo Metadata, analog https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/issues/36 von letzter Woche.

Viele Grüße
David

**Comment by cuehs** [comment]
Hi @icestorm972 , danke für den Hinweis. Das Problem ist uns bekannt und wir versuchen es zügig zu beheben.

**Comment by icestorm972** [comment]
Wohl doch eher grösseres Problem? 😔

Das "Zwischenupdate" am Freitag (2022-09-30) hatte übrigens sehr viele doppelte Zeilen im Metadaten csv (~6000 x 2, falls ich das richtig im Gedächtnis habe)

**Comment by cuehs** [comment]
Sollte wieder (relativ) stabil laufen.

**Comment by icestorm972** [comment]
Siehe https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/issues/40
