### ISSUE TITLE
Archivordner fehlt im Repository

### ISSUE THREAD

**Issue by rgerhards** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#4]
Im README wird ein Archivordner genannt und dessen Aufbau beschrieben.
```
Im Archivordner sind die täglichen Datenstände unter den Dateinamen
"JJJJ-MM-TT_SARS-CoV-2-Sequenzdaten_Deutschland.fasta.xz" und
"JJJJ-MM-TT_SARS-CoV-2-Sequenzdaten_Deutschland.csv.xz" abgelegt.
```
Dieser Ordner ist im Repository aber nicht enthalten. Er sollte vorzugsweise auch zur Verfügung gestellt werden oder alternativ die Readme.md Datei angepasst werden.

**Comment by cuehs** [comment]
Hi @rgerhards 
wir haben aufgrund von verschiedenen Rückmeldungen die zu recht anmerken, dass alle Altdaten in git automatisch archiviert werden den Archivordner gelöscht (vgl auch https://github.com/robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland/issues/10) Die Dokumentation muss hier noch angepasst werden.

**Comment by rgerhards** [comment]
@cuehs Danke für die rasche Antwort! git history ist ja immer etwas tricky, wenn da korrekturen reingefahren werden (also mehrere Commits pro Tag). Wenn ich es aber richtig sehe, wird für den jeweiligen Tagesentstand ein tag vergeben? Das wäre prima, denn dann kann man da ja einfach drüber iterieren.

**Comment by cuehs** [comment]
Ja im Normalfall sollte an jedem Tag ein Datenstand getagt sein. Außerdem enthält jede Tag alle Sequenzen, Metadaten und Lineages zurück bis Tag 0. Iterieren über die Tags ist nur nötig wenn die nutzende Person den spezifischen Stand für einen Tag haben möchte (z.B. relevant wenn Lineage-Calls für alte Sequenzen verändert werden).

**Comment by rgerhards** [comment]
> wenn die nutzende Person den spezifischen Stand für einen Tag haben möchte

genau drum ;-)

Danke nochmal!
