### ISSUE TITLE
Trouble importing zipped csv into R

### ISSUE THREAD

**Issue by lizacoyer** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#41]
Hi, 

I´m trying to download the https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/blob/master/SARS-CoV-2-Entwicklungslinien_Deutschland.csv.xz file programmatically into R, but Github blocks the download of binary files. Would it be possible to have this file as a CSV rather than zipping it? Additionally this would prevent your repository from growing too large.

Just FYI, what I am trying to do is 
```
URL <- "https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/blob/master/SARS-CoV-2-Entwicklungslinien_Deutschland.csv.xz?raw=true"
x <- getURL(URL, ssl.verifypeer=FALSE)
out <- read.csv(untar(textConnection(x)))
```
but the `getURL()` cannot read this properly.

Thanks in advance!

**Comment by icestorm972** [comment]
Maybe first download it as local file and then load the data?

Something like this:
https://stackoverflow.com/questions/64431076/r-cannot-download-gz-file-from-ftp-server

Or this:
https://stackoverflow.com/questions/9548630/read-gzipped-csv-directly-from-a-url-in-r

**Comment by HannesWuensche** [comment]
Hallo @lizacoyer,

wie wäre es mit diesem Link: 

https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/raw/master/SARS-CoV-2-Entwicklungslinien_Deutschland.csv.xz (verbirgt sich hinter dem Download Button)

Würden wir die Entwicklungslinien unverpackt bereitstellen wären es cs 180 MB. Wir müssten dann das git-lfs für die Daten verwenden, wofür eine Traffic-Beschränkung besteht. Wir wollen daher nur bei einer absoluten Notwendigkeit drauf zurückgreifen. 

Beste Grüße
@HannesWuensche 
für das Team RKI | Open Data
