### ISSUE TITLE
SARS-CoV-2-Sequenzdaten_Deutschland.fasta.xz - CRC-Fehler / Defektes Archiv

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#42]
Hi,

die "SARS-CoV-2-Sequenzdaten_Deutschland.fasta.xz" vom Sonntag Abend (2022-11-13) ist defekt/korrupt, siehe Screenshots.

Viele Grüße
David

Zur Info @HannesWuensche 

![crc_1](https://user-images.githubusercontent.com/20755156/201538337-1b787c89-5c9d-4d7c-ae7f-86d319e24371.PNG)
![crc_2](https://user-images.githubusercontent.com/20755156/201538338-378f8d42-1339-4f24-9968-ff0a253af162.PNG)

**Comment by axgraf** [comment]
Hi,
ich bekomme auch einen Fehler beim Entpacken der Datei **SARS-CoV-2-Sequenzdaten_Deutschland.fasta.xz**

![image](https://user-images.githubusercontent.com/16762600/201939236-636ad073-4c11-4c38-beb5-bcbfc13d1628.png)

Es scheint sich um das gleiche Problem wie bei @icestorm972 zu handeln.

Viele Grüße

Alex

**Comment by HannesWuensche** [comment]
Hallo @icestorm972 und @axgraf,

vielen Dank für die Rückmeldungen. 

Die original erzeugten Dateien sind nicht defekt. Mit den heruntergeladenen Dateien tritt der Fehler auch bei uns auf. 
Im Vergleich der MD5 Checksummen sehen wir den Fehler deutlich. Höchstwahrscheinlich ist ein interner Kopierprozess die Fehlerquelle. Wir werden versuchen das Problem schnellstmöglich zu beheben. 

Mit besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data

**Comment by axgraf** [comment]
Besten Dank, die Datei ist wieder lesbar.
