### ISSUE TITLE
documentation of PROCESSING_DATE missing in readme

### ISSUE THREAD

**Issue by rgerhards** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#5]
The CSV field PROCESSING_DATE is not documented. I assume it is the lab sequencing date?

**Comment by cuehs** [comment]
PROCESSING_DATE is an internal field, I am not sure why it is in the public repository. regardless: PROCESSING_DATE and RECEIVE_DATE both indicate when the sequence was uploaded to the RKI and when it was processed at RKI (usually that's the same day)

I just saw the twitter conversation: 
DATE_DRAW is can be used as a proxy of when an infection occurred.
PRIMEDIAGNOSTIC_LAB_PC can be used as a proxy for the location of the infection.

Unfortunately the number of sequences becomes only really informative after 10 days or so (the average delay between the date the sample is taken and uploaded to us).

**Comment by cuehs** [comment]
fixed by #12
