### ISSUE TITLE
README contains unclear explanation for meaning of SEQUENCING_REASON field

### ISSUE THREAD

**Issue by corneliusroemer** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#51]
Responding to this question https://github.com/GenSpectrum/LAPIS/issues/328#issuecomment-1673295486, I noticed that the explanation of the sequencing reason appears to not be entirely clear:

For example: `X (dem sequenzierenden Labor)` doesn't make sense by itself, it might be that an _unbekannt_ is missing

Also: "Grund für die Sequenzierung" appears not to match well with "Ja/Nein", maybe it is meant to say something like: "Targeted sequencing?" then "Ja/Nein" would make more sense:

<img width="1320" alt="image" src="https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/assets/25161793/2dee4754-53cf-4a16-a165-d5176d5cccf8">

**Comment by HannesWuensche** [comment]
Hallo @corneliusroemer,

thank you for your feedback.
You are entirely correct, and the 'unbekannt' got lost.
We will rework the documentation to correct this mistake and unclear description.

Best regrads
@HannesWuensche
