### ISSUE TITLE
2023-10-09? 

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#53]
Hi,

diese Woche scheint das Update (SARS-CoV-2-Sequenzdaten_Deutschland.fasta/tsv.xz) wieder ausgefallen zu sein.

Viele Grüße
David

**Comment by HannesWuensche** [comment]
Hallo @icestorm972,

die Sequenzdaten werden zukünftig immer Mittwochs, Nachmittags, bereitgestellt und wie bisher Montags. 
Wir bitten um Entschuldigung, dass wir die Ankündigung versäumt haben. 

Beste Grüße
@HannesWuensche 
für das Team RKI | Open Data
