### ISSUE TITLE
IMS-10285-CVDP-18B5CDB7-673D-47A6-984F-0BF3CF7F7DDF

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#54]
Hi,

zur Info: die Sequenz "IMS-10285-CVDP-18B5CDB7-673D-47A6-984F-0BF3CF7F7DDF" taucht nur in der .fasta.xz aber nicht in der .tsv.xz auf.

Viele Grüße
David

**Comment by TheBready** [comment]
Hi David,

Thank you for your report. Due to quality issues, the metadata of the sequence was removed. 
In the next release, the sequence will be removed as well.

Cheers,
Felix

**Comment by icestorm972** [comment]
Hi Felix,

Thank you for the info.
With todays release it was removed.

Cheers,
David
