### ISSUE TITLE
Update 2024-01-17

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#56]
Hi,

Gibt's diese Woche kein Update?
Oder gab es keine neuen empfangenen Sequenz-Daten (zeitverzögert wg Weihnachtspause) seit letztem Mi?

Viele Grüße 
David

**Comment by RKIOpenData** [comment]
Hi David,

leider gibt es gerade technische Probleme bei der Bereitstellung der Daten. Sodass wir diese Woche keinen neuen Datensatz zur Verfügung stellen können. Ab nächster Woche sollte dann wieder alles funktionieren.

beste Grüße
Knut Perseke
für das Team | RKI Open Data

**Comment by icestorm972** [comment]
Läuft wieder alles 👍
