### ISSUE TITLE
Update 2024-03-20 - fasta.xz not updated

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#57]
Hi,

Die SARS-CoV-2-Sequenzdaten_Deutschland.fasta.xz war im gestrigen Update nicht mit enthalten.
Gab es keine neuen Sequenzen oder ein Upload Problem?

Viele Grüße 
David

**Comment by RKIForschungsdatenmanagement** [comment]
Hi David,

wir haben hier nochmal nachgefragt. Genau, diese Woche gab es leider keine neuen Sequenzen

viele Grüße
Knut für das Team RKI | Open Data
