### ISSUE TITLE
No New Data Available Today (2024-07-17) or Data Transfer/Pipeline Problem?

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#58]
Hi,

the metadata was updated but not the SARS-CoV-2-Sequenzdaten_Deutschland.fasta/.tsv
Was there no data to update or a pipeline problem?

Best Regards
David

**Comment by HannesWuensche** [comment]
Hi @icestorm972,

thank you for your question.
There was no data update this week due to no new data. 

Beste Regards
@HannesWuensche 
RKI | Open Data
