### ISSUE TITLE
Ankündigung: Variablenanpassungen, Metadaten-Updates und mehr

### ISSUE THREAD

**Issue by HannesWuensche** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#59]
Liebe Nutzerinnen und Nutzer,

wir möchten euch darüber informieren, dass es in Kürze einige wichtige Änderungen an den Daten geben wird, die hier auf GitHub gehostet werden. Diese Änderungen betreffen sowohl die Struktur als auch teilweise den Inhalt der Daten.
Was ändert sich?

- Umbenennung von Variablen: Einige Variablen wurden umbenannt, um sie klarer und intuitiver zu gestalten, z. B. SEQUENCE.ID zu igs_id.
- Anpassung von Variablen: Die Variablen wurden an die generischen Anforderungen der IGS angepasst.
- Pangolin-Informationen: Alle Informationen zur Pangolin-Zuordnung sind jetzt in den Metadaten als JSON Blob integriert.
- Änderung des FASTA-Headers: Der FASTA-Header enthält jetzt auch die Version einer Sequenz im Format ><igs_id> version=<version>.

Was bedeutet das für euch?

- Überprüfung und Anpassung eurer Skripte: Bitte überprüft eure bestehenden Skripte und Anwendungen, die auf diese Datenquelle zugreifen, und nehmt die notwendigen Anpassungen vor.
- Aktualisierte Dokumentation: Die Dokumentation auf GitHub wurde entsprechend aktualisiert. Dort findet ihr detaillierte Informationen zu den Änderungen und deren Auswirkungen.
- Feedback und Unterstützung: Solltet ihr Fragen oder Anmerkungen haben, steht unser Team für Feedback und Unterstützung gerne zur Verfügung. Nutzt dazu bitte das Issue-Tracking-System auf GitHub oder kontaktiert uns direkt.

Wir danken euch für euer Verständnis und eurer Feedback. Die Änderungen sollen dazu beitragen, die Datenqualität und -nutzung weiter zu verbessern.

Vielen Dank und beste Grüße,
Das IGS-Team

Dear Users,

We would like to inform you about some important upcoming changes to the data hosted here on GitHub. These changes will affect both the structure and, in some cases, the content of the data.
What’s Changing?

- Renaming of Variables: Some variables have been renamed to make them clearer and more intuitive, e.g., SEQUENCE.ID is now igs_id.
- Variable Adjustments: Variables have been updated to align with the generic requirements of IGS.
- Pangolin Information: All Pangolin assignment data is now included in the metadata as a JSON blob.
- FASTA Header Update: The FASTA header now includes the sequence version in the format ><igs_id> version=<version>.

What Does This Mean for You?

-    Review and Update Your Scripts: Please review your existing scripts and applications that access this data source, and make any necessary adjustments.
-    Updated Documentation: The documentation on GitHub has been updated accordingly. You can find detailed information about the changes and their impacts there.
-    Feedback and Support: If you have any questions or comments, our team is available for feedback and support. Please use the issue-tracking system on GitHub or contact us directly.

We appreciate your understanding and feedback. These changes are intended to further improve data quality and usability.

Thank you and best regards,
The IGS Team

**Comment by icestorm972** [comment]
Hi,

Kann es sein, dass heute im Update nur die obige Formatanpassung gab, aber keine neuen Sequenzdaten (ggü. letzter Woche) dabei waren? 

Viele Grüße
David
