### ISSUE TITLE
Keine neuen Sequenzen mehr?

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#60]
Hi,

Heute gab es kein Update, und letzte Woche wurden nur die neu formatierten Daten (ohne neue Sequenzen) von vor 2 Wochen hochgeladen (https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/issues/59#issuecomment-2344544011).
Hängt da etwas in der neuen Pipeline?

Viele Grüße
David

**Comment by RKIOpenData** [comment]
Die Daten wurden heute aktualisiert. 
Viele Grüße
Simon | RKI Open Data Team
