### ISSUE TITLE
Upload to GISAID?

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#61]
Hi,

it looks like the upload to GISAID is broken since the pipeline/dataformat change (last upload on 2019-09-19).
Or is that intended?
 
See also [Discussion on Twitter/X](https://x.com/Mike_Honey_/status/1849197334825165087?t=dSNAn8Ivq4VFsqTxurahvQ&s=19)
![Screenshot_20241023-232126_X](https://github.com/user-attachments/assets/21929045-f1bc-44a0-a3a1-daa2e37e90a3)

Best Regards
David

**Comment by RKIOpenData** [comment]
Hi David,

thank you for reaching out. Yes, we're currently working on restoring the upload to GISAID. 
I'm afraid though that we can't yet give you a concrete timeframe as to when the GISAID upload will be restored. It is however a matter of high priority to restore it as soon as possible.

Kind regards
Simon

**Comment by SimonScholler** [comment]
Hi David,

a quick update from us: There has been a new upload to GISAID yesterday. We will try to return to weekly uploads from now but some technical challenges remain, so there might still be some hickups in the next weeks.

Kind regards
Simon | RKI Open Data Team
