### ISSUE TITLE
Einige Labore scheinen falsch zu randomisieren, entweder zu viel oder zu wenig Omikron in `REASON=N`

### ISSUE THREAD

**Issue by corneliusroemer** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#9]
Bei einer hierarchischen [Analyse](https://github.com/corneliusroemer/desh-data/blob/main/outlier_labs.ipynb) der Omikronausbreitung ist mir aufgefallen, dass es (mit Sicherheit) 3 Labore gibt die einen unmöglich hohen Omikron-Anteil in den angeblich repräsentativen Surveillance-Proben (markiert mit Grund `N`) hochladen.

Es handelt sich um Labore mit den `SENDING_PC`:
- 70193 (offenbar Labor Enders)
- 22767 (unklar welches Labor, Google zeigt keins)
- 24106 (offenbar Labor Krause)

Meine Vermutung ist, dass diese Labore Varianten-PCRs machen und dann aus Versehen den falschen Grund angeben.

Wenn man sich die Submissions der genannten Labore ansieht wurden da in letzter Zeit fast nur Omikrons übermittelt, und zwar in einem Maße das sehr inkonsistent ist mit dem Omikron-Anteil aller anderer deutschen Labore, siehe Plot unten.

Es gibt auch Labore, die möglicherweise zu wenige Omikrons ausweisen. Ein möglicher Mechanismus der dies begründen könnte:
1. Labore führen eine Varianten-PCR durch
2. Positive Proben werden als Verdachtsgrund sequenziert (mit `A` oder `Y`)
3. Aus den restlichen Proben werden Proben für die repräsentative Surveillance gezogen, dann mit `N` gelabelt.

Es ist klar, dass so die Randomisierung/Repräsentativität verletzt wird.

Es ist schwierig zu beweisen, dass dieser Fehler von manchen Laboren begangen wird aber ich kann es mir durchaus vorstellen.

Labore bei denen der Verdacht besteht sind auch im Plot unten identifizierbar, es handelt sich um Labore mit hohem Outlierness-Score und niedrigem Omikron-Anteil. Also relativ weit oben im Plot und im rechten Plot auf der linken Seite.

Wie zum Beispiel die Labore mit PLZ:
- 37077
- 56068
- 21079
- 74072

Diese Labore haben viele Sequenzen übermittelt aber (fast) keine (zu wenige) Omikrons.

Es würde sich wahrscheinlich lohnen, mal bei den genannten Laboren nachzufragen, ob sie möglicherweise die Instruktionen missverstanden haben.

![image](https://user-images.githubusercontent.com/25161793/147593201-73328016-566b-4478-9aab-4a0917e4db4d.png)

**Comment by cuehs** [comment]
@corneliusroemer Vielen Dank für deinen Hinweis. Wir haben die Anmerkungen an die entsprechenden Stellen am RKI weitergeleitet die sich dann mit den Laboren in Verbindung setzen.

**Comment by cuehs** [comment]
Könntest du einige beispielhafte IMS_IDs der Labore mit der PLZ 70193, 22767 und  24106  nennen?

**Comment by corneliusroemer** [comment]
@HannesWuensche Mich würde interessieren, ob es Rückmeldungen/Korrekturen von den Laboren gab zur Randomisierung, jetzt wo das Issue geschlossen wurde. Danke!
